### ISSUE TITLE
Ability to craft disallowed recipes

### ISSUE THREAD

**Issue by UnlimatedStone9** [jaredlll08/RecipeStages#22] opened 2018-08-26 00:14 UTC
Why is it that if I have a recipe for something using a recipe stages script it cannot be crafted when you don't have the appropriate stage but if I stage an items recipes it does nothing and is still craftable?

This script here adds a recipe with a stage that cannot be accessed until that stage
mods.recipestages.Recipes.addShapeless("stickysituation", <ore:cordageGeneral>, [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>, <ore:stickWood>]);

However this script here fails to prevent the player from crafting the item at all which allows items that shouldn't be craftable to be craftable, this is problematic if you don't want to individually remove and rewrite new recipes for an item
mods.recipestages.Recipes.setRecipeStage("stickysituation", "foragecraft:stick_bundle");

**Comment by jaredlll08** [comment] 2018-08-26 00:22
okay so, use gist for your scripts. github does weird formatting stuff.

I'm not even sure what the issue is, the way things work is

if I stage the recipe for `<minecraft:iron_leggings>` to stage `two`, I cannot craft them until I have stage `two`, so I'm not sure what you're experiencing...

**Comment by jaredlll08** [comment] 2018-08-26 00:26
didn't mean to close this, habit lol

**Comment by UnlimatedStone9** [comment] 2018-08-26 21:58
When I tell the item that its recipes are supposed to be staged by "stickysituation" the recipe is not removed until that stage is unlocked meaning it is still craftable even when I "setRecipeStage"

**Comment by jaredlll08** [comment] 2018-08-26 21:59
When you use setRecipeStage using the name, are you using the name of the item, or name of the recipe?

**Comment by UnlimatedStone9** [comment] 2018-08-26 22:00
I tell it to set the item to the chosen stage

**Comment by UnlimatedStone9** [comment] 2018-08-26 22:01
mods.recipestages.Recipes.setRecipeStage("one", "minecraft:boat");

This doesn't seem to do anything and refuses to set the items recipes to the chosen stage

**Comment by jaredlll08** [comment] 2018-08-26 22:55
That is because the method you are using is for recipe names. Not item names.

**Closed as completed by jaredlll08** 2018-08-26 22:55 UTC

**Comment by UnlimatedStone9** [comment] 2018-08-26 23:40
what would a recipe name be?

**Comment by UnlimatedStone9** [comment] 2018-08-26 23:40
this is the example shown on the crafttweaker page itself

**Comment by tofof** [comment] 2018-10-22 04:09
>That is because the method you are using is for recipe names. Not item names.

That line is literally from the [documentation ](https://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/RecipeStages/RecipeStages/) you @jaredlll08 link to in other issues.

```
Sets the stage of a non staged recipe.

//mods.recipestages.Recipes.setRecipeStage(String name, IItemStack output);
//mods.recipestages.Recipes.setRecipeStage(String name, String recipeName);

mods.recipestages.Recipes.setRecipeStage("one", <minecraft:stone_hoe>);
mods.recipestages.Recipes.setRecipeStage("one", "minecraft:boat");
```

Perhaps you would clarify whether the documentation is wrong or your closing-the-issue-comment was wrong?

**Comment by jaredlll08** [comment] 2018-10-22 05:00
Docs are right, as shown here, using the script: 
`mods.recipestages.Recipes.setRecipeStage("one", "minecraft:boat");`

![image](https://user-images.githubusercontent.com/5553605/47278283-f034cb00-d5c7-11e8-8eab-32e866570202.png)

I'll admit, I don't know what I was thinking when I closed this issue, but lets try some trouble shooting,

@UnlimatedStone9 show the recipe in JEI, make sure you are using the oak boat, even though I'm staging `"minecraft:boat"`, the other boats are unstaged, so this may be your issue.
![image](https://user-images.githubusercontent.com/5553605/47278306-240ff080-d5c8-11e8-80e2-ce6b25cc680a.png)
